name: jobera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  country_code_picker: ^3.0.0
  crypto: ^3.0.3
  dio: ^5.4.3
  file_picker: ^8.0.3
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pusher_beams: ^1.1.1
  pusher_channels_flutter: ^2.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets: 
   - assets/
  uses-material-design: true
